In [1]:
import pandas as pd
import numpy as np

In [5]:
steam200k

        151603712  The Elder Scrolls V Skyrim  purchase    1.0  0
0       151603712  The Elder Scrolls V Skyrim      play  273.0  0
1       151603712                   Fallout 4  purchase    1.0  0
2       151603712                   Fallout 4      play   87.0  0
3       151603712                       Spore  purchase    1.0  0
4       151603712                       Spore      play   14.9  0
...           ...                         ...       ...    ... ..
199994  128470551                 Titan Souls      play    1.5  0
199995  128470551  Grand Theft Auto Vice City  purchase    1.0  0
199996  128470551  Grand Theft Auto Vice City      play    1.5  0
199997  128470551                        RUSH  purchase    1.0  0
199998  128470551                        RUSH      play    1.4  0

[199999 rows x 5 columns]

In [3]:
steam200k = pd.read_csv("../data/steam200k.csv")

games = pd.read_csv("../data/games.csv").sort_values(by="app_id", ascending=True)

games_metadata = pd.read_json("../data/games_metadata.json", lines=True)
games = pd.merge(games, games_metadata, on="app_id")

games_and_user_playtime = pd.merge(games, steam200k, on="title")
games_and_user_playtime

KeyError: 'title'

In [12]:
name_basics

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0025164"
1,nm0000002,Lauren Bacall,1924,2014,"actress,miscellaneous,soundtrack","tt0037382,tt0075213,tt0038355,tt0045891"
2,nm0000003,Brigitte Bardot,1934,2025,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,1949,1982,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"
...,...,...,...,...,...,...
15382278,nm9993714,Romeo del Rosario,\N,\N,"animation_department,art_department","tt11657662,tt14069590,tt2455546"
15382279,nm9993716,Essias Loberg,\N,\N,\N,\N
15382280,nm9993717,Harikrishnan Rajan,\N,\N,cinematographer,tt8736744
15382281,nm9993718,Aayush Nair,\N,\N,cinematographer,tt8736744
15382282,nm9993719,Andre Hill,\N,\N,\N,\N

In [13]:
title_basics

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short
...,...,...,...,...,...,...,...,...,...
12541384,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2009,\N,\N,Drama
12541385,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,Drama
12541386,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,Drama
12541387,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
12541388,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy"

In [14]:
title_principals

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2,nm0005690,director,\N,\N
2,tt0000001,3,nm0005690,producer,producer,\N
3,tt0000001,4,nm0374658,cinematographer,director of photography,\N
4,tt0000002,1,nm0721526,director,\N,\N
...,...,...,...,...,...,...
99764716,tt9916880,17,nm0996406,director,principal director,\N
99764717,tt9916880,18,nm1482639,writer,\N,\N
99764718,tt9916880,19,nm2586970,writer,books,\N
99764719,tt9916880,20,nm1594058,producer,producer,\N
99764720,tt9916880,21,nm1482639,producer,producer,\N

In [15]:
title_ratings

            tconst  averageRating  numVotes
0        tt0000001            5.7      2210
1        tt0000002            5.5       317
2        tt0000003            6.4      2340
3        tt0000004            5.1       191
4        tt0000005            6.2      3055
...            ...            ...       ...
1676737  tt9916846            5.3         7
1676738  tt9916848            5.2         7
1676739  tt9916850            6.0         7
1676740  tt9916852            5.7         7
1676741  tt9916880            7.6        11

[1676742 rows x 3 columns]

In [ ]:
df_titles = pd.read_csv('../data/title.basics.tsv', sep='\t')
df_names = pd.read_csv('../data/name.basics.tsv', sep='\t')

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,NaN,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,NaN,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,NaN,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,NaN,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,NaN,1,Short
...,...,...,...,...,...,...,...,...,...
12541384,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2009,NaN,NaN,Drama
12541385,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,NaN,NaN,Drama
12541386,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,NaN,NaN,Drama
12541387,tt9916856,short,The Wind,The Wind,0,2015,NaN,27,Short
12541388,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,NaN,10,"Adventure,Animation,Comedy"

In [22]:
# Nettoyage rapide (IMDb utilise '\N' pour les valeurs manquantes)
df_titles.replace('\\N', np.nan, inplace=True)
df_names.replace('\\N', np.nan, inplace=True)

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0025164"
1,nm0000002,Lauren Bacall,1924,2014,"actress,miscellaneous,soundtrack","tt0037382,tt0075213,tt0038355,tt0045891"
2,nm0000003,Brigitte Bardot,1934,2025,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,1949,1982,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"
...,...,...,...,...,...,...
15382278,nm9993714,Romeo del Rosario,NaN,NaN,"animation_department,art_department","tt11657662,tt14069590,tt2455546"
15382279,nm9993716,Essias Loberg,NaN,NaN,NaN,NaN
15382280,nm9993717,Harikrishnan Rajan,NaN,NaN,cinematographer,tt8736744
15382281,nm9993718,Aayush Nair,NaN,NaN,cinematographer,tt8736744
15382282,nm9993719,Andre Hill,NaN,NaN,NaN,NaN

In [ ]:
def process_imdb_data(titles_df, names_df):
    # 1. Préparation : On veut lier les noms aux films.
    # On transforme la colonne 'knownForTitles' en lignes individuelles
    # pour pouvoir faire une jointure simple.
    
    # On supprime les lignes où il n'y a pas de titres connus
    names_exploded = names_df.dropna(subset=['knownForTitles'])
    
    # On "explose" la chaîne de caractères (ex: "tt1,tt2" -> deux lignes)
    names_exploded = names_exploded.assign(tconst=names_exploded['knownForTitles'].str.split(','))
    names_exploded = names_exploded.explode('tconst')
    
    # 2. Jointure : On lie les noms des acteurs aux films
    # On ne garde que les colonnes utiles pour éviter d'alourdir le DF
    names_subset = names_exploded[['tconst', 'primaryName']]
    
    # On regroupe les noms par film (pour avoir une liste de noms par film)
    names_grouped = names_subset.groupby('tconst')['primaryName'].apply(
    lambda x: ', '.join(x.astype(str))
    ).reset_index()
    
    # 3. Fusion finale avec title_basics
    df_enriched = pd.merge(titles_df, names_grouped, on='tconst', how='left')
    
    # Remplissage des NaN pour les films sans noms associés
    df_enriched['primaryName'] = df_enriched['primaryName'].fillna('')
    
    return df_enriched

In [24]:
process_imdb_data(title_basics, name_basics)

TypeError: sequence item 612501: expected str instance, float found